name: BlockBoxes
version: '${project.version}'
main: com.cham.blockboxes.BlockBoxes
api-version: '1.20'
commands:
  lootcount:
    aliases:
      - lc
  createtable:
    aliases:
      - ct
  showtables:
    aliases:
      - st
  givetable:
    usage: /givetable player table
    aliases:
      - givet
  edittable:
    aliases:
      - et
  tableremove:
    aliases:
      - tr

