name: BlockBoxes
version: '${project.version}'
main: com.cham.blockboxes.BlockBoxes
api-version: '1.20'
commands:
  createtable:
    aliases:
      - ct
  gettables:
    aliases:
      - gt
  givetable:
    usage: </givetable> tableName player
    aliases:
      - givet
  tablehelp:
    aliases:
      - th
  edittable:
    aliases:
      - et
  tableremove:
    aliases:
      - tr
  tablereload:
